[versions]
gradle = "8.2.2"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.21"
androidx-core = "1.17.0"
androidx-appcompat = "1.7.1"
material = "1.13.0"
androidx-activity = "1.11.0"
constraintlayout = "2.2.1"
androidx-room = "2.8.3"
androidx-fragment = "1.8.9"
gson = "2.13.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0" }
junit = { group = "junit", name = "junit", version = "4.13.2" }

[plugins]
